FROM alpine:latest AS ssl-generator
RUN apk add --update openssl && \
    openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost" \
    -keyout /server.key \
    -out /server.crt
    
FROM node:16 AS build-client
WORKDIR /app

COPY /src/UrlShortener.WebApplication/ClientApp/package*.json ./
RUN npm ci

COPY /src/UrlShortener.WebApplication/ClientApp .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=ssl-generator /server.crt /server.key /etc/nginx/
COPY --from=build-client /app/build /usr/share/nginx/html
COPY nginx-client.conf /etc/nginx/conf.d/default.conf